default:
  bot:
    return_home: به صفحه اصلی برگشتید
    done: با موفقیت ثبت شد
    cancel: لغو
    invalid_button: ها؟
    duplicate_answer: قبلا پر کردی
    quizzes:
      - name: ترین
        desc: در این بخش می‌توانید ترین‌های دوره رو مشخص کنید:)
        questions:
          - سگ‌ترین فرد دوره کیست؟
          - گربه‌ترین فرد دوره کیست؟
          - ریشوترین فرد دوره کیست؟ جواب قطعا عرشیا نیست
      - name: ناشانس
        desc: در این بخش می‌توانید یک پیام ناشناس به هم دوره‌ای هاتون بدید
        questions:
          - سم طرف
          - پیامت
